source 'https://gitcafe.com/akuandev/Specs.git'
platform :ios, '6.0'

pod 'Mantle', '~> 1.5'
pod 'Masonry', '~> 0.5.3'
pod 'AFNetworking', '~> 2.3.1'
pod 'FMDB', '~> 2.3'
pod 'RegexKitLite', '~> 4.0'
pod 'NSString-UrlEncode', '~> 1.1.0'
pod 'ASIHTTPRequest', '~> 1.8.2'
